'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
'
Namespace wsFactura
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsTbFacturaSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class wsTbFactura
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private TbFacturaConsultarFacturasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbFacturaConsultarFacturasFiltrosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbFacturaconsultarFacturasReportesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbFacturaConsultarFacturaBusquedaMantenimientoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbFacturaConsultarFacturaNumeroSiguienteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbFacturaConsultarFacturaMontoTotalOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbFacturaInsertarFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbFacturaActualizarFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbFacturaActualizarFacturaMontoTotalOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbFacturaImprimirFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbFacturaAnularFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CapaPresentacion.My.MySettings.Default.CapaPresentacion_wsFactura_wsTbFactura
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event TbFacturaConsultarFacturasCompleted As TbFacturaConsultarFacturasCompletedEventHandler
        
        '''<remarks/>
        Public Event TbFacturaConsultarFacturasFiltrosCompleted As TbFacturaConsultarFacturasFiltrosCompletedEventHandler
        
        '''<remarks/>
        Public Event TbFacturaconsultarFacturasReportesCompleted As TbFacturaconsultarFacturasReportesCompletedEventHandler
        
        '''<remarks/>
        Public Event TbFacturaConsultarFacturaBusquedaMantenimientoCompleted As TbFacturaConsultarFacturaBusquedaMantenimientoCompletedEventHandler
        
        '''<remarks/>
        Public Event TbFacturaConsultarFacturaNumeroSiguienteCompleted As TbFacturaConsultarFacturaNumeroSiguienteCompletedEventHandler
        
        '''<remarks/>
        Public Event TbFacturaConsultarFacturaMontoTotalCompleted As TbFacturaConsultarFacturaMontoTotalCompletedEventHandler
        
        '''<remarks/>
        Public Event TbFacturaInsertarFacturaCompleted As TbFacturaInsertarFacturaCompletedEventHandler
        
        '''<remarks/>
        Public Event TbFacturaActualizarFacturaCompleted As TbFacturaActualizarFacturaCompletedEventHandler
        
        '''<remarks/>
        Public Event TbFacturaActualizarFacturaMontoTotalCompleted As TbFacturaActualizarFacturaMontoTotalCompletedEventHandler
        
        '''<remarks/>
        Public Event TbFacturaImprimirFacturaCompleted As TbFacturaImprimirFacturaCompletedEventHandler
        
        '''<remarks/>
        Public Event TbFacturaAnularFacturaCompleted As TbFacturaAnularFacturaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbFacturaConsultarFacturas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbFacturaConsultarFacturas(ByVal pTipoFactura As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TbFacturaConsultarFacturas", New Object() {pTipoFactura})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbFacturaConsultarFacturasAsync(ByVal pTipoFactura As Integer)
            Me.TbFacturaConsultarFacturasAsync(pTipoFactura, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbFacturaConsultarFacturasAsync(ByVal pTipoFactura As Integer, ByVal userState As Object)
            If (Me.TbFacturaConsultarFacturasOperationCompleted Is Nothing) Then
                Me.TbFacturaConsultarFacturasOperationCompleted = AddressOf Me.OnTbFacturaConsultarFacturasOperationCompleted
            End If
            Me.InvokeAsync("TbFacturaConsultarFacturas", New Object() {pTipoFactura}, Me.TbFacturaConsultarFacturasOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbFacturaConsultarFacturasOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbFacturaConsultarFacturasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbFacturaConsultarFacturasCompleted(Me, New TbFacturaConsultarFacturasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbFacturaConsultarFacturasFiltros", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbFacturaConsultarFacturasFiltros(ByVal pIdFactura As Integer, ByVal pNombreCliente As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TbFacturaConsultarFacturasFiltros", New Object() {pIdFactura, pNombreCliente})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbFacturaConsultarFacturasFiltrosAsync(ByVal pIdFactura As Integer, ByVal pNombreCliente As String)
            Me.TbFacturaConsultarFacturasFiltrosAsync(pIdFactura, pNombreCliente, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbFacturaConsultarFacturasFiltrosAsync(ByVal pIdFactura As Integer, ByVal pNombreCliente As String, ByVal userState As Object)
            If (Me.TbFacturaConsultarFacturasFiltrosOperationCompleted Is Nothing) Then
                Me.TbFacturaConsultarFacturasFiltrosOperationCompleted = AddressOf Me.OnTbFacturaConsultarFacturasFiltrosOperationCompleted
            End If
            Me.InvokeAsync("TbFacturaConsultarFacturasFiltros", New Object() {pIdFactura, pNombreCliente}, Me.TbFacturaConsultarFacturasFiltrosOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbFacturaConsultarFacturasFiltrosOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbFacturaConsultarFacturasFiltrosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbFacturaConsultarFacturasFiltrosCompleted(Me, New TbFacturaConsultarFacturasFiltrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbFacturaconsultarFacturasReportes", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbFacturaconsultarFacturasReportes(ByVal pPersona As Persona, ByVal FechIni As Date, ByVal FechFin As Date) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TbFacturaconsultarFacturasReportes", New Object() {pPersona, FechIni, FechFin})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbFacturaconsultarFacturasReportesAsync(ByVal pPersona As Persona, ByVal FechIni As Date, ByVal FechFin As Date)
            Me.TbFacturaconsultarFacturasReportesAsync(pPersona, FechIni, FechFin, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbFacturaconsultarFacturasReportesAsync(ByVal pPersona As Persona, ByVal FechIni As Date, ByVal FechFin As Date, ByVal userState As Object)
            If (Me.TbFacturaconsultarFacturasReportesOperationCompleted Is Nothing) Then
                Me.TbFacturaconsultarFacturasReportesOperationCompleted = AddressOf Me.OnTbFacturaconsultarFacturasReportesOperationCompleted
            End If
            Me.InvokeAsync("TbFacturaconsultarFacturasReportes", New Object() {pPersona, FechIni, FechFin}, Me.TbFacturaconsultarFacturasReportesOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbFacturaconsultarFacturasReportesOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbFacturaconsultarFacturasReportesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbFacturaconsultarFacturasReportesCompleted(Me, New TbFacturaconsultarFacturasReportesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbFacturaConsultarFacturaBusquedaMantenimiento", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbFacturaConsultarFacturaBusquedaMantenimiento(ByVal pFactura As Factura) As Factura
            Dim results() As Object = Me.Invoke("TbFacturaConsultarFacturaBusquedaMantenimiento", New Object() {pFactura})
            Return CType(results(0),Factura)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbFacturaConsultarFacturaBusquedaMantenimientoAsync(ByVal pFactura As Factura)
            Me.TbFacturaConsultarFacturaBusquedaMantenimientoAsync(pFactura, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbFacturaConsultarFacturaBusquedaMantenimientoAsync(ByVal pFactura As Factura, ByVal userState As Object)
            If (Me.TbFacturaConsultarFacturaBusquedaMantenimientoOperationCompleted Is Nothing) Then
                Me.TbFacturaConsultarFacturaBusquedaMantenimientoOperationCompleted = AddressOf Me.OnTbFacturaConsultarFacturaBusquedaMantenimientoOperationCompleted
            End If
            Me.InvokeAsync("TbFacturaConsultarFacturaBusquedaMantenimiento", New Object() {pFactura}, Me.TbFacturaConsultarFacturaBusquedaMantenimientoOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbFacturaConsultarFacturaBusquedaMantenimientoOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbFacturaConsultarFacturaBusquedaMantenimientoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbFacturaConsultarFacturaBusquedaMantenimientoCompleted(Me, New TbFacturaConsultarFacturaBusquedaMantenimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbFacturaConsultarFacturaNumeroSiguiente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbFacturaConsultarFacturaNumeroSiguiente() As Integer
            Dim results() As Object = Me.Invoke("TbFacturaConsultarFacturaNumeroSiguiente", New Object(-1) {})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbFacturaConsultarFacturaNumeroSiguienteAsync()
            Me.TbFacturaConsultarFacturaNumeroSiguienteAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbFacturaConsultarFacturaNumeroSiguienteAsync(ByVal userState As Object)
            If (Me.TbFacturaConsultarFacturaNumeroSiguienteOperationCompleted Is Nothing) Then
                Me.TbFacturaConsultarFacturaNumeroSiguienteOperationCompleted = AddressOf Me.OnTbFacturaConsultarFacturaNumeroSiguienteOperationCompleted
            End If
            Me.InvokeAsync("TbFacturaConsultarFacturaNumeroSiguiente", New Object(-1) {}, Me.TbFacturaConsultarFacturaNumeroSiguienteOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbFacturaConsultarFacturaNumeroSiguienteOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbFacturaConsultarFacturaNumeroSiguienteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbFacturaConsultarFacturaNumeroSiguienteCompleted(Me, New TbFacturaConsultarFacturaNumeroSiguienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbFacturaConsultarFacturaMontoTotal", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbFacturaConsultarFacturaMontoTotal(ByVal pIdFactura As Integer) As Double
            Dim results() As Object = Me.Invoke("TbFacturaConsultarFacturaMontoTotal", New Object() {pIdFactura})
            Return CType(results(0),Double)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbFacturaConsultarFacturaMontoTotalAsync(ByVal pIdFactura As Integer)
            Me.TbFacturaConsultarFacturaMontoTotalAsync(pIdFactura, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbFacturaConsultarFacturaMontoTotalAsync(ByVal pIdFactura As Integer, ByVal userState As Object)
            If (Me.TbFacturaConsultarFacturaMontoTotalOperationCompleted Is Nothing) Then
                Me.TbFacturaConsultarFacturaMontoTotalOperationCompleted = AddressOf Me.OnTbFacturaConsultarFacturaMontoTotalOperationCompleted
            End If
            Me.InvokeAsync("TbFacturaConsultarFacturaMontoTotal", New Object() {pIdFactura}, Me.TbFacturaConsultarFacturaMontoTotalOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbFacturaConsultarFacturaMontoTotalOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbFacturaConsultarFacturaMontoTotalCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbFacturaConsultarFacturaMontoTotalCompleted(Me, New TbFacturaConsultarFacturaMontoTotalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbFacturaInsertarFactura", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbFacturaInsertarFactura(ByVal pFactura As Factura, ByVal pFecha As Integer) As String
            Dim results() As Object = Me.Invoke("TbFacturaInsertarFactura", New Object() {pFactura, pFecha})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbFacturaInsertarFacturaAsync(ByVal pFactura As Factura, ByVal pFecha As Integer)
            Me.TbFacturaInsertarFacturaAsync(pFactura, pFecha, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbFacturaInsertarFacturaAsync(ByVal pFactura As Factura, ByVal pFecha As Integer, ByVal userState As Object)
            If (Me.TbFacturaInsertarFacturaOperationCompleted Is Nothing) Then
                Me.TbFacturaInsertarFacturaOperationCompleted = AddressOf Me.OnTbFacturaInsertarFacturaOperationCompleted
            End If
            Me.InvokeAsync("TbFacturaInsertarFactura", New Object() {pFactura, pFecha}, Me.TbFacturaInsertarFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbFacturaInsertarFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbFacturaInsertarFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbFacturaInsertarFacturaCompleted(Me, New TbFacturaInsertarFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbFacturaActualizarFactura", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbFacturaActualizarFactura(ByVal pFactura As Factura) As String
            Dim results() As Object = Me.Invoke("TbFacturaActualizarFactura", New Object() {pFactura})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbFacturaActualizarFacturaAsync(ByVal pFactura As Factura)
            Me.TbFacturaActualizarFacturaAsync(pFactura, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbFacturaActualizarFacturaAsync(ByVal pFactura As Factura, ByVal userState As Object)
            If (Me.TbFacturaActualizarFacturaOperationCompleted Is Nothing) Then
                Me.TbFacturaActualizarFacturaOperationCompleted = AddressOf Me.OnTbFacturaActualizarFacturaOperationCompleted
            End If
            Me.InvokeAsync("TbFacturaActualizarFactura", New Object() {pFactura}, Me.TbFacturaActualizarFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbFacturaActualizarFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbFacturaActualizarFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbFacturaActualizarFacturaCompleted(Me, New TbFacturaActualizarFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbFacturaActualizarFacturaMontoTotal", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbFacturaActualizarFacturaMontoTotal(ByVal pFactura As Factura) As String
            Dim results() As Object = Me.Invoke("TbFacturaActualizarFacturaMontoTotal", New Object() {pFactura})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbFacturaActualizarFacturaMontoTotalAsync(ByVal pFactura As Factura)
            Me.TbFacturaActualizarFacturaMontoTotalAsync(pFactura, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbFacturaActualizarFacturaMontoTotalAsync(ByVal pFactura As Factura, ByVal userState As Object)
            If (Me.TbFacturaActualizarFacturaMontoTotalOperationCompleted Is Nothing) Then
                Me.TbFacturaActualizarFacturaMontoTotalOperationCompleted = AddressOf Me.OnTbFacturaActualizarFacturaMontoTotalOperationCompleted
            End If
            Me.InvokeAsync("TbFacturaActualizarFacturaMontoTotal", New Object() {pFactura}, Me.TbFacturaActualizarFacturaMontoTotalOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbFacturaActualizarFacturaMontoTotalOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbFacturaActualizarFacturaMontoTotalCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbFacturaActualizarFacturaMontoTotalCompleted(Me, New TbFacturaActualizarFacturaMontoTotalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbFacturaImprimirFactura", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbFacturaImprimirFactura(ByVal pFactura As Factura) As String
            Dim results() As Object = Me.Invoke("TbFacturaImprimirFactura", New Object() {pFactura})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbFacturaImprimirFacturaAsync(ByVal pFactura As Factura)
            Me.TbFacturaImprimirFacturaAsync(pFactura, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbFacturaImprimirFacturaAsync(ByVal pFactura As Factura, ByVal userState As Object)
            If (Me.TbFacturaImprimirFacturaOperationCompleted Is Nothing) Then
                Me.TbFacturaImprimirFacturaOperationCompleted = AddressOf Me.OnTbFacturaImprimirFacturaOperationCompleted
            End If
            Me.InvokeAsync("TbFacturaImprimirFactura", New Object() {pFactura}, Me.TbFacturaImprimirFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbFacturaImprimirFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbFacturaImprimirFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbFacturaImprimirFacturaCompleted(Me, New TbFacturaImprimirFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbFacturaAnularFactura", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbFacturaAnularFactura(ByVal pFactura As Factura) As String
            Dim results() As Object = Me.Invoke("TbFacturaAnularFactura", New Object() {pFactura})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbFacturaAnularFacturaAsync(ByVal pFactura As Factura)
            Me.TbFacturaAnularFacturaAsync(pFactura, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbFacturaAnularFacturaAsync(ByVal pFactura As Factura, ByVal userState As Object)
            If (Me.TbFacturaAnularFacturaOperationCompleted Is Nothing) Then
                Me.TbFacturaAnularFacturaOperationCompleted = AddressOf Me.OnTbFacturaAnularFacturaOperationCompleted
            End If
            Me.InvokeAsync("TbFacturaAnularFactura", New Object() {pFactura}, Me.TbFacturaAnularFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbFacturaAnularFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbFacturaAnularFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbFacturaAnularFacturaCompleted(Me, New TbFacturaAnularFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Persona
        
        Private correoField As String
        
        Private cedulaField As String
        
        Private nombreField As String
        
        Private apellido1Field As String
        
        Private apellido2Field As String
        
        Private fechaNacimientoField As Date
        
        Private direccionField As String
        
        Private telefonoField As String
        
        Private sexoField As String
        
        Private contrasenaField As String
        
        Private idRolField As Integer
        
        Private idEstadoField As Integer
        
        '''<comentarios/>
        Public Property Correo() As String
            Get
                Return Me.correoField
            End Get
            Set
                Me.correoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Cedula() As String
            Get
                Return Me.cedulaField
            End Get
            Set
                Me.cedulaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Apellido1() As String
            Get
                Return Me.apellido1Field
            End Get
            Set
                Me.apellido1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Apellido2() As String
            Get
                Return Me.apellido2Field
            End Get
            Set
                Me.apellido2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaNacimiento() As Date
            Get
                Return Me.fechaNacimientoField
            End Get
            Set
                Me.fechaNacimientoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Telefono() As String
            Get
                Return Me.telefonoField
            End Get
            Set
                Me.telefonoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Sexo() As String
            Get
                Return Me.sexoField
            End Get
            Set
                Me.sexoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Contrasena() As String
            Get
                Return Me.contrasenaField
            End Get
            Set
                Me.contrasenaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IdRol() As Integer
            Get
                Return Me.idRolField
            End Get
            Set
                Me.idRolField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IdEstado() As Integer
            Get
                Return Me.idEstadoField
            End Get
            Set
                Me.idEstadoField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Factura
        
        Private idFacturaField As Integer
        
        Private correoField As String
        
        Private fechaEmisionField As Date
        
        Private fechaVencimientoField As Date
        
        Private montoTotalField As Double
        
        Private montoCanceladoField As Double
        
        Private saldoActualField As Double
        
        Private idEstadoField As Integer
        
        '''<comentarios/>
        Public Property IdFactura() As Integer
            Get
                Return Me.idFacturaField
            End Get
            Set
                Me.idFacturaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Correo() As String
            Get
                Return Me.correoField
            End Get
            Set
                Me.correoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaEmision() As Date
            Get
                Return Me.fechaEmisionField
            End Get
            Set
                Me.fechaEmisionField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaVencimiento() As Date
            Get
                Return Me.fechaVencimientoField
            End Get
            Set
                Me.fechaVencimientoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MontoTotal() As Double
            Get
                Return Me.montoTotalField
            End Get
            Set
                Me.montoTotalField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MontoCancelado() As Double
            Get
                Return Me.montoCanceladoField
            End Get
            Set
                Me.montoCanceladoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SaldoActual() As Double
            Get
                Return Me.saldoActualField
            End Get
            Set
                Me.saldoActualField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IdEstado() As Integer
            Get
                Return Me.idEstadoField
            End Get
            Set
                Me.idEstadoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbFacturaConsultarFacturasCompletedEventHandler(ByVal sender As Object, ByVal e As TbFacturaConsultarFacturasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbFacturaConsultarFacturasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbFacturaConsultarFacturasFiltrosCompletedEventHandler(ByVal sender As Object, ByVal e As TbFacturaConsultarFacturasFiltrosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbFacturaConsultarFacturasFiltrosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbFacturaconsultarFacturasReportesCompletedEventHandler(ByVal sender As Object, ByVal e As TbFacturaconsultarFacturasReportesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbFacturaconsultarFacturasReportesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbFacturaConsultarFacturaBusquedaMantenimientoCompletedEventHandler(ByVal sender As Object, ByVal e As TbFacturaConsultarFacturaBusquedaMantenimientoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbFacturaConsultarFacturaBusquedaMantenimientoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Factura
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Factura)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbFacturaConsultarFacturaNumeroSiguienteCompletedEventHandler(ByVal sender As Object, ByVal e As TbFacturaConsultarFacturaNumeroSiguienteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbFacturaConsultarFacturaNumeroSiguienteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbFacturaConsultarFacturaMontoTotalCompletedEventHandler(ByVal sender As Object, ByVal e As TbFacturaConsultarFacturaMontoTotalCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbFacturaConsultarFacturaMontoTotalCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Double
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Double)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbFacturaInsertarFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As TbFacturaInsertarFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbFacturaInsertarFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbFacturaActualizarFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As TbFacturaActualizarFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbFacturaActualizarFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbFacturaActualizarFacturaMontoTotalCompletedEventHandler(ByVal sender As Object, ByVal e As TbFacturaActualizarFacturaMontoTotalCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbFacturaActualizarFacturaMontoTotalCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbFacturaImprimirFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As TbFacturaImprimirFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbFacturaImprimirFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbFacturaAnularFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As TbFacturaAnularFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbFacturaAnularFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
