'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
'
Namespace wsPersona
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsTbPersonaSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class wsTbPersona
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private TbPersonaConsultarPersonasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbPersonaConsultarClientesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbPersonaConsultarPersonasFiltrosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbPersonaConsultarClientesFiltrosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbPersonaConsultarPersonaLoginOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbPersonaConsultarPersonaBusquedaContraseñaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbPersonaConsultarPersonaBusquedaMantenimientoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbPersonaInsertarPersonaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbPersonaActualizarPersonaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbPersonaActualizarPersonaContraseñaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbPersonaEliminarPersonaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CapaPresentacion.My.MySettings.Default.CapaPresentacion_wsPersona_wsTbPersona
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event TbPersonaConsultarPersonasCompleted As TbPersonaConsultarPersonasCompletedEventHandler
        
        '''<remarks/>
        Public Event TbPersonaConsultarClientesCompleted As TbPersonaConsultarClientesCompletedEventHandler
        
        '''<remarks/>
        Public Event TbPersonaConsultarPersonasFiltrosCompleted As TbPersonaConsultarPersonasFiltrosCompletedEventHandler
        
        '''<remarks/>
        Public Event TbPersonaConsultarClientesFiltrosCompleted As TbPersonaConsultarClientesFiltrosCompletedEventHandler
        
        '''<remarks/>
        Public Event TbPersonaConsultarPersonaLoginCompleted As TbPersonaConsultarPersonaLoginCompletedEventHandler
        
        '''<remarks/>
        Public Event TbPersonaConsultarPersonaBusquedaContraseñaCompleted As TbPersonaConsultarPersonaBusquedaContraseñaCompletedEventHandler
        
        '''<remarks/>
        Public Event TbPersonaConsultarPersonaBusquedaMantenimientoCompleted As TbPersonaConsultarPersonaBusquedaMantenimientoCompletedEventHandler
        
        '''<remarks/>
        Public Event TbPersonaInsertarPersonaCompleted As TbPersonaInsertarPersonaCompletedEventHandler
        
        '''<remarks/>
        Public Event TbPersonaActualizarPersonaCompleted As TbPersonaActualizarPersonaCompletedEventHandler
        
        '''<remarks/>
        Public Event TbPersonaActualizarPersonaContraseñaCompleted As TbPersonaActualizarPersonaContraseñaCompletedEventHandler
        
        '''<remarks/>
        Public Event TbPersonaEliminarPersonaCompleted As TbPersonaEliminarPersonaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbPersonaConsultarPersonas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbPersonaConsultarPersonas() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TbPersonaConsultarPersonas", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbPersonaConsultarPersonasAsync()
            Me.TbPersonaConsultarPersonasAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbPersonaConsultarPersonasAsync(ByVal userState As Object)
            If (Me.TbPersonaConsultarPersonasOperationCompleted Is Nothing) Then
                Me.TbPersonaConsultarPersonasOperationCompleted = AddressOf Me.OnTbPersonaConsultarPersonasOperationCompleted
            End If
            Me.InvokeAsync("TbPersonaConsultarPersonas", New Object(-1) {}, Me.TbPersonaConsultarPersonasOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbPersonaConsultarPersonasOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbPersonaConsultarPersonasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbPersonaConsultarPersonasCompleted(Me, New TbPersonaConsultarPersonasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbPersonaConsultarClientes", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbPersonaConsultarClientes() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TbPersonaConsultarClientes", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbPersonaConsultarClientesAsync()
            Me.TbPersonaConsultarClientesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbPersonaConsultarClientesAsync(ByVal userState As Object)
            If (Me.TbPersonaConsultarClientesOperationCompleted Is Nothing) Then
                Me.TbPersonaConsultarClientesOperationCompleted = AddressOf Me.OnTbPersonaConsultarClientesOperationCompleted
            End If
            Me.InvokeAsync("TbPersonaConsultarClientes", New Object(-1) {}, Me.TbPersonaConsultarClientesOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbPersonaConsultarClientesOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbPersonaConsultarClientesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbPersonaConsultarClientesCompleted(Me, New TbPersonaConsultarClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbPersonaConsultarPersonasFiltros", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbPersonaConsultarPersonasFiltros(ByVal pCedula As String, ByVal pNombreCompleto As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TbPersonaConsultarPersonasFiltros", New Object() {pCedula, pNombreCompleto})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbPersonaConsultarPersonasFiltrosAsync(ByVal pCedula As String, ByVal pNombreCompleto As String)
            Me.TbPersonaConsultarPersonasFiltrosAsync(pCedula, pNombreCompleto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbPersonaConsultarPersonasFiltrosAsync(ByVal pCedula As String, ByVal pNombreCompleto As String, ByVal userState As Object)
            If (Me.TbPersonaConsultarPersonasFiltrosOperationCompleted Is Nothing) Then
                Me.TbPersonaConsultarPersonasFiltrosOperationCompleted = AddressOf Me.OnTbPersonaConsultarPersonasFiltrosOperationCompleted
            End If
            Me.InvokeAsync("TbPersonaConsultarPersonasFiltros", New Object() {pCedula, pNombreCompleto}, Me.TbPersonaConsultarPersonasFiltrosOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbPersonaConsultarPersonasFiltrosOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbPersonaConsultarPersonasFiltrosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbPersonaConsultarPersonasFiltrosCompleted(Me, New TbPersonaConsultarPersonasFiltrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbPersonaConsultarClientesFiltros", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbPersonaConsultarClientesFiltros(ByVal pCedula As String, ByVal pNombreCompleto As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TbPersonaConsultarClientesFiltros", New Object() {pCedula, pNombreCompleto})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbPersonaConsultarClientesFiltrosAsync(ByVal pCedula As String, ByVal pNombreCompleto As String)
            Me.TbPersonaConsultarClientesFiltrosAsync(pCedula, pNombreCompleto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbPersonaConsultarClientesFiltrosAsync(ByVal pCedula As String, ByVal pNombreCompleto As String, ByVal userState As Object)
            If (Me.TbPersonaConsultarClientesFiltrosOperationCompleted Is Nothing) Then
                Me.TbPersonaConsultarClientesFiltrosOperationCompleted = AddressOf Me.OnTbPersonaConsultarClientesFiltrosOperationCompleted
            End If
            Me.InvokeAsync("TbPersonaConsultarClientesFiltros", New Object() {pCedula, pNombreCompleto}, Me.TbPersonaConsultarClientesFiltrosOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbPersonaConsultarClientesFiltrosOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbPersonaConsultarClientesFiltrosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbPersonaConsultarClientesFiltrosCompleted(Me, New TbPersonaConsultarClientesFiltrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbPersonaConsultarPersonaLogin", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbPersonaConsultarPersonaLogin(ByVal pPersona As Persona) As Persona
            Dim results() As Object = Me.Invoke("TbPersonaConsultarPersonaLogin", New Object() {pPersona})
            Return CType(results(0),Persona)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbPersonaConsultarPersonaLoginAsync(ByVal pPersona As Persona)
            Me.TbPersonaConsultarPersonaLoginAsync(pPersona, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbPersonaConsultarPersonaLoginAsync(ByVal pPersona As Persona, ByVal userState As Object)
            If (Me.TbPersonaConsultarPersonaLoginOperationCompleted Is Nothing) Then
                Me.TbPersonaConsultarPersonaLoginOperationCompleted = AddressOf Me.OnTbPersonaConsultarPersonaLoginOperationCompleted
            End If
            Me.InvokeAsync("TbPersonaConsultarPersonaLogin", New Object() {pPersona}, Me.TbPersonaConsultarPersonaLoginOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbPersonaConsultarPersonaLoginOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbPersonaConsultarPersonaLoginCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbPersonaConsultarPersonaLoginCompleted(Me, New TbPersonaConsultarPersonaLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbPersonaConsultarPersonaBusquedaContraseña", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbPersonaConsultarPersonaBusquedaContraseña(ByVal pPersona As Persona) As Persona
            Dim results() As Object = Me.Invoke("TbPersonaConsultarPersonaBusquedaContraseña", New Object() {pPersona})
            Return CType(results(0),Persona)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbPersonaConsultarPersonaBusquedaContraseñaAsync(ByVal pPersona As Persona)
            Me.TbPersonaConsultarPersonaBusquedaContraseñaAsync(pPersona, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbPersonaConsultarPersonaBusquedaContraseñaAsync(ByVal pPersona As Persona, ByVal userState As Object)
            If (Me.TbPersonaConsultarPersonaBusquedaContraseñaOperationCompleted Is Nothing) Then
                Me.TbPersonaConsultarPersonaBusquedaContraseñaOperationCompleted = AddressOf Me.OnTbPersonaConsultarPersonaBusquedaContraseñaOperationCompleted
            End If
            Me.InvokeAsync("TbPersonaConsultarPersonaBusquedaContraseña", New Object() {pPersona}, Me.TbPersonaConsultarPersonaBusquedaContraseñaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbPersonaConsultarPersonaBusquedaContraseñaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbPersonaConsultarPersonaBusquedaContraseñaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbPersonaConsultarPersonaBusquedaContraseñaCompleted(Me, New TbPersonaConsultarPersonaBusquedaContraseñaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbPersonaConsultarPersonaBusquedaMantenimiento", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbPersonaConsultarPersonaBusquedaMantenimiento(ByVal pPersona As Persona) As Persona
            Dim results() As Object = Me.Invoke("TbPersonaConsultarPersonaBusquedaMantenimiento", New Object() {pPersona})
            Return CType(results(0),Persona)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbPersonaConsultarPersonaBusquedaMantenimientoAsync(ByVal pPersona As Persona)
            Me.TbPersonaConsultarPersonaBusquedaMantenimientoAsync(pPersona, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbPersonaConsultarPersonaBusquedaMantenimientoAsync(ByVal pPersona As Persona, ByVal userState As Object)
            If (Me.TbPersonaConsultarPersonaBusquedaMantenimientoOperationCompleted Is Nothing) Then
                Me.TbPersonaConsultarPersonaBusquedaMantenimientoOperationCompleted = AddressOf Me.OnTbPersonaConsultarPersonaBusquedaMantenimientoOperationCompleted
            End If
            Me.InvokeAsync("TbPersonaConsultarPersonaBusquedaMantenimiento", New Object() {pPersona}, Me.TbPersonaConsultarPersonaBusquedaMantenimientoOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbPersonaConsultarPersonaBusquedaMantenimientoOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbPersonaConsultarPersonaBusquedaMantenimientoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbPersonaConsultarPersonaBusquedaMantenimientoCompleted(Me, New TbPersonaConsultarPersonaBusquedaMantenimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbPersonaInsertarPersona", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbPersonaInsertarPersona(ByVal pPersona As Persona) As String
            Dim results() As Object = Me.Invoke("TbPersonaInsertarPersona", New Object() {pPersona})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbPersonaInsertarPersonaAsync(ByVal pPersona As Persona)
            Me.TbPersonaInsertarPersonaAsync(pPersona, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbPersonaInsertarPersonaAsync(ByVal pPersona As Persona, ByVal userState As Object)
            If (Me.TbPersonaInsertarPersonaOperationCompleted Is Nothing) Then
                Me.TbPersonaInsertarPersonaOperationCompleted = AddressOf Me.OnTbPersonaInsertarPersonaOperationCompleted
            End If
            Me.InvokeAsync("TbPersonaInsertarPersona", New Object() {pPersona}, Me.TbPersonaInsertarPersonaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbPersonaInsertarPersonaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbPersonaInsertarPersonaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbPersonaInsertarPersonaCompleted(Me, New TbPersonaInsertarPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbPersonaActualizarPersona", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbPersonaActualizarPersona(ByVal pPersona As Persona) As String
            Dim results() As Object = Me.Invoke("TbPersonaActualizarPersona", New Object() {pPersona})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbPersonaActualizarPersonaAsync(ByVal pPersona As Persona)
            Me.TbPersonaActualizarPersonaAsync(pPersona, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbPersonaActualizarPersonaAsync(ByVal pPersona As Persona, ByVal userState As Object)
            If (Me.TbPersonaActualizarPersonaOperationCompleted Is Nothing) Then
                Me.TbPersonaActualizarPersonaOperationCompleted = AddressOf Me.OnTbPersonaActualizarPersonaOperationCompleted
            End If
            Me.InvokeAsync("TbPersonaActualizarPersona", New Object() {pPersona}, Me.TbPersonaActualizarPersonaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbPersonaActualizarPersonaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbPersonaActualizarPersonaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbPersonaActualizarPersonaCompleted(Me, New TbPersonaActualizarPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbPersonaActualizarPersonaContraseña", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbPersonaActualizarPersonaContraseña(ByVal pPersona As Persona) As String
            Dim results() As Object = Me.Invoke("TbPersonaActualizarPersonaContraseña", New Object() {pPersona})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbPersonaActualizarPersonaContraseñaAsync(ByVal pPersona As Persona)
            Me.TbPersonaActualizarPersonaContraseñaAsync(pPersona, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbPersonaActualizarPersonaContraseñaAsync(ByVal pPersona As Persona, ByVal userState As Object)
            If (Me.TbPersonaActualizarPersonaContraseñaOperationCompleted Is Nothing) Then
                Me.TbPersonaActualizarPersonaContraseñaOperationCompleted = AddressOf Me.OnTbPersonaActualizarPersonaContraseñaOperationCompleted
            End If
            Me.InvokeAsync("TbPersonaActualizarPersonaContraseña", New Object() {pPersona}, Me.TbPersonaActualizarPersonaContraseñaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbPersonaActualizarPersonaContraseñaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbPersonaActualizarPersonaContraseñaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbPersonaActualizarPersonaContraseñaCompleted(Me, New TbPersonaActualizarPersonaContraseñaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbPersonaEliminarPersona", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbPersonaEliminarPersona(ByVal pPersona As Persona) As String
            Dim results() As Object = Me.Invoke("TbPersonaEliminarPersona", New Object() {pPersona})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbPersonaEliminarPersonaAsync(ByVal pPersona As Persona)
            Me.TbPersonaEliminarPersonaAsync(pPersona, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbPersonaEliminarPersonaAsync(ByVal pPersona As Persona, ByVal userState As Object)
            If (Me.TbPersonaEliminarPersonaOperationCompleted Is Nothing) Then
                Me.TbPersonaEliminarPersonaOperationCompleted = AddressOf Me.OnTbPersonaEliminarPersonaOperationCompleted
            End If
            Me.InvokeAsync("TbPersonaEliminarPersona", New Object() {pPersona}, Me.TbPersonaEliminarPersonaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbPersonaEliminarPersonaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbPersonaEliminarPersonaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbPersonaEliminarPersonaCompleted(Me, New TbPersonaEliminarPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Persona
        
        Private correoField As String
        
        Private cedulaField As String
        
        Private nombreField As String
        
        Private apellido1Field As String
        
        Private apellido2Field As String
        
        Private fechaNacimientoField As Date
        
        Private direccionField As String
        
        Private telefonoField As String
        
        Private sexoField As String
        
        Private contrasenaField As String
        
        Private idRolField As Integer
        
        Private idEstadoField As Integer
        
        '''<comentarios/>
        Public Property Correo() As String
            Get
                Return Me.correoField
            End Get
            Set
                Me.correoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Cedula() As String
            Get
                Return Me.cedulaField
            End Get
            Set
                Me.cedulaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Apellido1() As String
            Get
                Return Me.apellido1Field
            End Get
            Set
                Me.apellido1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Apellido2() As String
            Get
                Return Me.apellido2Field
            End Get
            Set
                Me.apellido2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaNacimiento() As Date
            Get
                Return Me.fechaNacimientoField
            End Get
            Set
                Me.fechaNacimientoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Telefono() As String
            Get
                Return Me.telefonoField
            End Get
            Set
                Me.telefonoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Sexo() As String
            Get
                Return Me.sexoField
            End Get
            Set
                Me.sexoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Contrasena() As String
            Get
                Return Me.contrasenaField
            End Get
            Set
                Me.contrasenaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IdRol() As Integer
            Get
                Return Me.idRolField
            End Get
            Set
                Me.idRolField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IdEstado() As Integer
            Get
                Return Me.idEstadoField
            End Get
            Set
                Me.idEstadoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbPersonaConsultarPersonasCompletedEventHandler(ByVal sender As Object, ByVal e As TbPersonaConsultarPersonasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbPersonaConsultarPersonasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbPersonaConsultarClientesCompletedEventHandler(ByVal sender As Object, ByVal e As TbPersonaConsultarClientesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbPersonaConsultarClientesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbPersonaConsultarPersonasFiltrosCompletedEventHandler(ByVal sender As Object, ByVal e As TbPersonaConsultarPersonasFiltrosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbPersonaConsultarPersonasFiltrosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbPersonaConsultarClientesFiltrosCompletedEventHandler(ByVal sender As Object, ByVal e As TbPersonaConsultarClientesFiltrosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbPersonaConsultarClientesFiltrosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbPersonaConsultarPersonaLoginCompletedEventHandler(ByVal sender As Object, ByVal e As TbPersonaConsultarPersonaLoginCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbPersonaConsultarPersonaLoginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Persona
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Persona)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbPersonaConsultarPersonaBusquedaContraseñaCompletedEventHandler(ByVal sender As Object, ByVal e As TbPersonaConsultarPersonaBusquedaContraseñaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbPersonaConsultarPersonaBusquedaContraseñaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Persona
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Persona)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbPersonaConsultarPersonaBusquedaMantenimientoCompletedEventHandler(ByVal sender As Object, ByVal e As TbPersonaConsultarPersonaBusquedaMantenimientoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbPersonaConsultarPersonaBusquedaMantenimientoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Persona
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Persona)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbPersonaInsertarPersonaCompletedEventHandler(ByVal sender As Object, ByVal e As TbPersonaInsertarPersonaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbPersonaInsertarPersonaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbPersonaActualizarPersonaCompletedEventHandler(ByVal sender As Object, ByVal e As TbPersonaActualizarPersonaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbPersonaActualizarPersonaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbPersonaActualizarPersonaContraseñaCompletedEventHandler(ByVal sender As Object, ByVal e As TbPersonaActualizarPersonaContraseñaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbPersonaActualizarPersonaContraseñaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbPersonaEliminarPersonaCompletedEventHandler(ByVal sender As Object, ByVal e As TbPersonaEliminarPersonaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbPersonaEliminarPersonaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
