'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
'
Namespace wsDetalleRecibo
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsTbDetalleReciboSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class wsTbDetalleRecibo
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private TbDetalleReciboConsultarDetallesReciboOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbDetalleReciboConsultarDetalleReciboOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbDetalleReciboInsertarDetalleReciboOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbDetalleReciboActualizarDetalleReciboOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbDetalleReciboEliminarDetalleReciboOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CapaPresentacion.My.MySettings.Default.CapaPresentacion_wsDetalleRecibo_wsTbDetalleRecibo
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event TbDetalleReciboConsultarDetallesReciboCompleted As TbDetalleReciboConsultarDetallesReciboCompletedEventHandler
        
        '''<remarks/>
        Public Event TbDetalleReciboConsultarDetalleReciboCompleted As TbDetalleReciboConsultarDetalleReciboCompletedEventHandler
        
        '''<remarks/>
        Public Event TbDetalleReciboInsertarDetalleReciboCompleted As TbDetalleReciboInsertarDetalleReciboCompletedEventHandler
        
        '''<remarks/>
        Public Event TbDetalleReciboActualizarDetalleReciboCompleted As TbDetalleReciboActualizarDetalleReciboCompletedEventHandler
        
        '''<remarks/>
        Public Event TbDetalleReciboEliminarDetalleReciboCompleted As TbDetalleReciboEliminarDetalleReciboCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbDetalleReciboConsultarDetallesRecibo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbDetalleReciboConsultarDetallesRecibo(ByVal pIdRecibo As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TbDetalleReciboConsultarDetallesRecibo", New Object() {pIdRecibo})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbDetalleReciboConsultarDetallesReciboAsync(ByVal pIdRecibo As Integer)
            Me.TbDetalleReciboConsultarDetallesReciboAsync(pIdRecibo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbDetalleReciboConsultarDetallesReciboAsync(ByVal pIdRecibo As Integer, ByVal userState As Object)
            If (Me.TbDetalleReciboConsultarDetallesReciboOperationCompleted Is Nothing) Then
                Me.TbDetalleReciboConsultarDetallesReciboOperationCompleted = AddressOf Me.OnTbDetalleReciboConsultarDetallesReciboOperationCompleted
            End If
            Me.InvokeAsync("TbDetalleReciboConsultarDetallesRecibo", New Object() {pIdRecibo}, Me.TbDetalleReciboConsultarDetallesReciboOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbDetalleReciboConsultarDetallesReciboOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbDetalleReciboConsultarDetallesReciboCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbDetalleReciboConsultarDetallesReciboCompleted(Me, New TbDetalleReciboConsultarDetallesReciboCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbDetalleReciboConsultarDetalleRecibo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbDetalleReciboConsultarDetalleRecibo(ByVal pDetalleRecibo As DetalleRecibo) As DetalleRecibo
            Dim results() As Object = Me.Invoke("TbDetalleReciboConsultarDetalleRecibo", New Object() {pDetalleRecibo})
            Return CType(results(0),DetalleRecibo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbDetalleReciboConsultarDetalleReciboAsync(ByVal pDetalleRecibo As DetalleRecibo)
            Me.TbDetalleReciboConsultarDetalleReciboAsync(pDetalleRecibo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbDetalleReciboConsultarDetalleReciboAsync(ByVal pDetalleRecibo As DetalleRecibo, ByVal userState As Object)
            If (Me.TbDetalleReciboConsultarDetalleReciboOperationCompleted Is Nothing) Then
                Me.TbDetalleReciboConsultarDetalleReciboOperationCompleted = AddressOf Me.OnTbDetalleReciboConsultarDetalleReciboOperationCompleted
            End If
            Me.InvokeAsync("TbDetalleReciboConsultarDetalleRecibo", New Object() {pDetalleRecibo}, Me.TbDetalleReciboConsultarDetalleReciboOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbDetalleReciboConsultarDetalleReciboOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbDetalleReciboConsultarDetalleReciboCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbDetalleReciboConsultarDetalleReciboCompleted(Me, New TbDetalleReciboConsultarDetalleReciboCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbDetalleReciboInsertarDetalleRecibo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbDetalleReciboInsertarDetalleRecibo(ByVal pDetalleRecibo As DetalleRecibo) As String
            Dim results() As Object = Me.Invoke("TbDetalleReciboInsertarDetalleRecibo", New Object() {pDetalleRecibo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbDetalleReciboInsertarDetalleReciboAsync(ByVal pDetalleRecibo As DetalleRecibo)
            Me.TbDetalleReciboInsertarDetalleReciboAsync(pDetalleRecibo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbDetalleReciboInsertarDetalleReciboAsync(ByVal pDetalleRecibo As DetalleRecibo, ByVal userState As Object)
            If (Me.TbDetalleReciboInsertarDetalleReciboOperationCompleted Is Nothing) Then
                Me.TbDetalleReciboInsertarDetalleReciboOperationCompleted = AddressOf Me.OnTbDetalleReciboInsertarDetalleReciboOperationCompleted
            End If
            Me.InvokeAsync("TbDetalleReciboInsertarDetalleRecibo", New Object() {pDetalleRecibo}, Me.TbDetalleReciboInsertarDetalleReciboOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbDetalleReciboInsertarDetalleReciboOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbDetalleReciboInsertarDetalleReciboCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbDetalleReciboInsertarDetalleReciboCompleted(Me, New TbDetalleReciboInsertarDetalleReciboCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbDetalleReciboActualizarDetalleRecibo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbDetalleReciboActualizarDetalleRecibo(ByVal pDetalleRecibo As DetalleRecibo) As String
            Dim results() As Object = Me.Invoke("TbDetalleReciboActualizarDetalleRecibo", New Object() {pDetalleRecibo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbDetalleReciboActualizarDetalleReciboAsync(ByVal pDetalleRecibo As DetalleRecibo)
            Me.TbDetalleReciboActualizarDetalleReciboAsync(pDetalleRecibo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbDetalleReciboActualizarDetalleReciboAsync(ByVal pDetalleRecibo As DetalleRecibo, ByVal userState As Object)
            If (Me.TbDetalleReciboActualizarDetalleReciboOperationCompleted Is Nothing) Then
                Me.TbDetalleReciboActualizarDetalleReciboOperationCompleted = AddressOf Me.OnTbDetalleReciboActualizarDetalleReciboOperationCompleted
            End If
            Me.InvokeAsync("TbDetalleReciboActualizarDetalleRecibo", New Object() {pDetalleRecibo}, Me.TbDetalleReciboActualizarDetalleReciboOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbDetalleReciboActualizarDetalleReciboOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbDetalleReciboActualizarDetalleReciboCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbDetalleReciboActualizarDetalleReciboCompleted(Me, New TbDetalleReciboActualizarDetalleReciboCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbDetalleReciboEliminarDetalleRecibo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbDetalleReciboEliminarDetalleRecibo(ByVal pDetalleRecibo As DetalleRecibo) As String
            Dim results() As Object = Me.Invoke("TbDetalleReciboEliminarDetalleRecibo", New Object() {pDetalleRecibo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbDetalleReciboEliminarDetalleReciboAsync(ByVal pDetalleRecibo As DetalleRecibo)
            Me.TbDetalleReciboEliminarDetalleReciboAsync(pDetalleRecibo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbDetalleReciboEliminarDetalleReciboAsync(ByVal pDetalleRecibo As DetalleRecibo, ByVal userState As Object)
            If (Me.TbDetalleReciboEliminarDetalleReciboOperationCompleted Is Nothing) Then
                Me.TbDetalleReciboEliminarDetalleReciboOperationCompleted = AddressOf Me.OnTbDetalleReciboEliminarDetalleReciboOperationCompleted
            End If
            Me.InvokeAsync("TbDetalleReciboEliminarDetalleRecibo", New Object() {pDetalleRecibo}, Me.TbDetalleReciboEliminarDetalleReciboOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbDetalleReciboEliminarDetalleReciboOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbDetalleReciboEliminarDetalleReciboCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbDetalleReciboEliminarDetalleReciboCompleted(Me, New TbDetalleReciboEliminarDetalleReciboCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DetalleRecibo
        
        Private idReciboField As Integer
        
        Private idDetalleReciboField As Integer
        
        Private idFacturaField As Integer
        
        Private montoCanceladoField As Double
        
        '''<comentarios/>
        Public Property IdRecibo() As Integer
            Get
                Return Me.idReciboField
            End Get
            Set
                Me.idReciboField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IdDetalleRecibo() As Integer
            Get
                Return Me.idDetalleReciboField
            End Get
            Set
                Me.idDetalleReciboField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IdFactura() As Integer
            Get
                Return Me.idFacturaField
            End Get
            Set
                Me.idFacturaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MontoCancelado() As Double
            Get
                Return Me.montoCanceladoField
            End Get
            Set
                Me.montoCanceladoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbDetalleReciboConsultarDetallesReciboCompletedEventHandler(ByVal sender As Object, ByVal e As TbDetalleReciboConsultarDetallesReciboCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbDetalleReciboConsultarDetallesReciboCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbDetalleReciboConsultarDetalleReciboCompletedEventHandler(ByVal sender As Object, ByVal e As TbDetalleReciboConsultarDetalleReciboCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbDetalleReciboConsultarDetalleReciboCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DetalleRecibo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DetalleRecibo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbDetalleReciboInsertarDetalleReciboCompletedEventHandler(ByVal sender As Object, ByVal e As TbDetalleReciboInsertarDetalleReciboCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbDetalleReciboInsertarDetalleReciboCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbDetalleReciboActualizarDetalleReciboCompletedEventHandler(ByVal sender As Object, ByVal e As TbDetalleReciboActualizarDetalleReciboCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbDetalleReciboActualizarDetalleReciboCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbDetalleReciboEliminarDetalleReciboCompletedEventHandler(ByVal sender As Object, ByVal e As TbDetalleReciboEliminarDetalleReciboCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbDetalleReciboEliminarDetalleReciboCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
