'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
'
Namespace wsImpuesto
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsTbImpuestoSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class wsTbImpuesto
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private TbImpuestoConsultarImpuestosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbImpuestoConsultarImpuestosFiltrosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbImpuestoConsultarImpuestoBusquedaMantenimientoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbImpuestoInsertarImpuestoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbImpuestoActualizarImpuestoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbIMpuestoEliminarImpuestoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CapaPresentacion.My.MySettings.Default.CapaPresentacion_wsImpuesto_wsTbImpuesto
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event TbImpuestoConsultarImpuestosCompleted As TbImpuestoConsultarImpuestosCompletedEventHandler
        
        '''<remarks/>
        Public Event TbImpuestoConsultarImpuestosFiltrosCompleted As TbImpuestoConsultarImpuestosFiltrosCompletedEventHandler
        
        '''<remarks/>
        Public Event TbImpuestoConsultarImpuestoBusquedaMantenimientoCompleted As TbImpuestoConsultarImpuestoBusquedaMantenimientoCompletedEventHandler
        
        '''<remarks/>
        Public Event TbImpuestoInsertarImpuestoCompleted As TbImpuestoInsertarImpuestoCompletedEventHandler
        
        '''<remarks/>
        Public Event TbImpuestoActualizarImpuestoCompleted As TbImpuestoActualizarImpuestoCompletedEventHandler
        
        '''<remarks/>
        Public Event TbIMpuestoEliminarImpuestoCompleted As TbIMpuestoEliminarImpuestoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbImpuestoConsultarImpuestos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbImpuestoConsultarImpuestos() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TbImpuestoConsultarImpuestos", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbImpuestoConsultarImpuestosAsync()
            Me.TbImpuestoConsultarImpuestosAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbImpuestoConsultarImpuestosAsync(ByVal userState As Object)
            If (Me.TbImpuestoConsultarImpuestosOperationCompleted Is Nothing) Then
                Me.TbImpuestoConsultarImpuestosOperationCompleted = AddressOf Me.OnTbImpuestoConsultarImpuestosOperationCompleted
            End If
            Me.InvokeAsync("TbImpuestoConsultarImpuestos", New Object(-1) {}, Me.TbImpuestoConsultarImpuestosOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbImpuestoConsultarImpuestosOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbImpuestoConsultarImpuestosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbImpuestoConsultarImpuestosCompleted(Me, New TbImpuestoConsultarImpuestosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbImpuestoConsultarImpuestosFiltros", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbImpuestoConsultarImpuestosFiltros(ByVal pDescripcion As String, ByVal pPorcentajeImpuesto As Double) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TbImpuestoConsultarImpuestosFiltros", New Object() {pDescripcion, pPorcentajeImpuesto})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbImpuestoConsultarImpuestosFiltrosAsync(ByVal pDescripcion As String, ByVal pPorcentajeImpuesto As Double)
            Me.TbImpuestoConsultarImpuestosFiltrosAsync(pDescripcion, pPorcentajeImpuesto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbImpuestoConsultarImpuestosFiltrosAsync(ByVal pDescripcion As String, ByVal pPorcentajeImpuesto As Double, ByVal userState As Object)
            If (Me.TbImpuestoConsultarImpuestosFiltrosOperationCompleted Is Nothing) Then
                Me.TbImpuestoConsultarImpuestosFiltrosOperationCompleted = AddressOf Me.OnTbImpuestoConsultarImpuestosFiltrosOperationCompleted
            End If
            Me.InvokeAsync("TbImpuestoConsultarImpuestosFiltros", New Object() {pDescripcion, pPorcentajeImpuesto}, Me.TbImpuestoConsultarImpuestosFiltrosOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbImpuestoConsultarImpuestosFiltrosOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbImpuestoConsultarImpuestosFiltrosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbImpuestoConsultarImpuestosFiltrosCompleted(Me, New TbImpuestoConsultarImpuestosFiltrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbImpuestoConsultarImpuestoBusquedaMantenimiento", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbImpuestoConsultarImpuestoBusquedaMantenimiento(ByVal pImpuesto As Impuesto) As Impuesto
            Dim results() As Object = Me.Invoke("TbImpuestoConsultarImpuestoBusquedaMantenimiento", New Object() {pImpuesto})
            Return CType(results(0),Impuesto)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbImpuestoConsultarImpuestoBusquedaMantenimientoAsync(ByVal pImpuesto As Impuesto)
            Me.TbImpuestoConsultarImpuestoBusquedaMantenimientoAsync(pImpuesto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbImpuestoConsultarImpuestoBusquedaMantenimientoAsync(ByVal pImpuesto As Impuesto, ByVal userState As Object)
            If (Me.TbImpuestoConsultarImpuestoBusquedaMantenimientoOperationCompleted Is Nothing) Then
                Me.TbImpuestoConsultarImpuestoBusquedaMantenimientoOperationCompleted = AddressOf Me.OnTbImpuestoConsultarImpuestoBusquedaMantenimientoOperationCompleted
            End If
            Me.InvokeAsync("TbImpuestoConsultarImpuestoBusquedaMantenimiento", New Object() {pImpuesto}, Me.TbImpuestoConsultarImpuestoBusquedaMantenimientoOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbImpuestoConsultarImpuestoBusquedaMantenimientoOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbImpuestoConsultarImpuestoBusquedaMantenimientoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbImpuestoConsultarImpuestoBusquedaMantenimientoCompleted(Me, New TbImpuestoConsultarImpuestoBusquedaMantenimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbImpuestoInsertarImpuesto", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbImpuestoInsertarImpuesto(ByVal pImpuesto As Impuesto) As String
            Dim results() As Object = Me.Invoke("TbImpuestoInsertarImpuesto", New Object() {pImpuesto})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbImpuestoInsertarImpuestoAsync(ByVal pImpuesto As Impuesto)
            Me.TbImpuestoInsertarImpuestoAsync(pImpuesto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbImpuestoInsertarImpuestoAsync(ByVal pImpuesto As Impuesto, ByVal userState As Object)
            If (Me.TbImpuestoInsertarImpuestoOperationCompleted Is Nothing) Then
                Me.TbImpuestoInsertarImpuestoOperationCompleted = AddressOf Me.OnTbImpuestoInsertarImpuestoOperationCompleted
            End If
            Me.InvokeAsync("TbImpuestoInsertarImpuesto", New Object() {pImpuesto}, Me.TbImpuestoInsertarImpuestoOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbImpuestoInsertarImpuestoOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbImpuestoInsertarImpuestoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbImpuestoInsertarImpuestoCompleted(Me, New TbImpuestoInsertarImpuestoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbImpuestoActualizarImpuesto", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbImpuestoActualizarImpuesto(ByVal pImpuesto As Impuesto) As String
            Dim results() As Object = Me.Invoke("TbImpuestoActualizarImpuesto", New Object() {pImpuesto})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbImpuestoActualizarImpuestoAsync(ByVal pImpuesto As Impuesto)
            Me.TbImpuestoActualizarImpuestoAsync(pImpuesto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbImpuestoActualizarImpuestoAsync(ByVal pImpuesto As Impuesto, ByVal userState As Object)
            If (Me.TbImpuestoActualizarImpuestoOperationCompleted Is Nothing) Then
                Me.TbImpuestoActualizarImpuestoOperationCompleted = AddressOf Me.OnTbImpuestoActualizarImpuestoOperationCompleted
            End If
            Me.InvokeAsync("TbImpuestoActualizarImpuesto", New Object() {pImpuesto}, Me.TbImpuestoActualizarImpuestoOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbImpuestoActualizarImpuestoOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbImpuestoActualizarImpuestoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbImpuestoActualizarImpuestoCompleted(Me, New TbImpuestoActualizarImpuestoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbIMpuestoEliminarImpuesto", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbIMpuestoEliminarImpuesto(ByVal pImpuesto As Impuesto) As String
            Dim results() As Object = Me.Invoke("TbIMpuestoEliminarImpuesto", New Object() {pImpuesto})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbIMpuestoEliminarImpuestoAsync(ByVal pImpuesto As Impuesto)
            Me.TbIMpuestoEliminarImpuestoAsync(pImpuesto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbIMpuestoEliminarImpuestoAsync(ByVal pImpuesto As Impuesto, ByVal userState As Object)
            If (Me.TbIMpuestoEliminarImpuestoOperationCompleted Is Nothing) Then
                Me.TbIMpuestoEliminarImpuestoOperationCompleted = AddressOf Me.OnTbIMpuestoEliminarImpuestoOperationCompleted
            End If
            Me.InvokeAsync("TbIMpuestoEliminarImpuesto", New Object() {pImpuesto}, Me.TbIMpuestoEliminarImpuestoOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbIMpuestoEliminarImpuestoOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbIMpuestoEliminarImpuestoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbIMpuestoEliminarImpuestoCompleted(Me, New TbIMpuestoEliminarImpuestoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Impuesto
        
        Private idImpuestoField As Integer
        
        Private descripcionField As String
        
        Private porcentajeImpuestoField As Double
        
        '''<comentarios/>
        Public Property IdImpuesto() As Integer
            Get
                Return Me.idImpuestoField
            End Get
            Set
                Me.idImpuestoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PorcentajeImpuesto() As Double
            Get
                Return Me.porcentajeImpuestoField
            End Get
            Set
                Me.porcentajeImpuestoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbImpuestoConsultarImpuestosCompletedEventHandler(ByVal sender As Object, ByVal e As TbImpuestoConsultarImpuestosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbImpuestoConsultarImpuestosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbImpuestoConsultarImpuestosFiltrosCompletedEventHandler(ByVal sender As Object, ByVal e As TbImpuestoConsultarImpuestosFiltrosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbImpuestoConsultarImpuestosFiltrosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbImpuestoConsultarImpuestoBusquedaMantenimientoCompletedEventHandler(ByVal sender As Object, ByVal e As TbImpuestoConsultarImpuestoBusquedaMantenimientoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbImpuestoConsultarImpuestoBusquedaMantenimientoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Impuesto
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Impuesto)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbImpuestoInsertarImpuestoCompletedEventHandler(ByVal sender As Object, ByVal e As TbImpuestoInsertarImpuestoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbImpuestoInsertarImpuestoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbImpuestoActualizarImpuestoCompletedEventHandler(ByVal sender As Object, ByVal e As TbImpuestoActualizarImpuestoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbImpuestoActualizarImpuestoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbIMpuestoEliminarImpuestoCompletedEventHandler(ByVal sender As Object, ByVal e As TbIMpuestoEliminarImpuestoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbIMpuestoEliminarImpuestoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
