'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
'
Namespace wsRol
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsTbRolSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class wsTbRol
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private TbRolConsultarRolesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbRolConsultarRolOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbRolInsertarRolOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbRolActualizarRolOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbRolEliminarRolOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CapaPresentacion.My.MySettings.Default.CapaPresentacion_wsRol_wsTbRol
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event TbRolConsultarRolesCompleted As TbRolConsultarRolesCompletedEventHandler
        
        '''<remarks/>
        Public Event TbRolConsultarRolCompleted As TbRolConsultarRolCompletedEventHandler
        
        '''<remarks/>
        Public Event TbRolInsertarRolCompleted As TbRolInsertarRolCompletedEventHandler
        
        '''<remarks/>
        Public Event TbRolActualizarRolCompleted As TbRolActualizarRolCompletedEventHandler
        
        '''<remarks/>
        Public Event TbRolEliminarRolCompleted As TbRolEliminarRolCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbRolConsultarRoles", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbRolConsultarRoles() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TbRolConsultarRoles", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbRolConsultarRolesAsync()
            Me.TbRolConsultarRolesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbRolConsultarRolesAsync(ByVal userState As Object)
            If (Me.TbRolConsultarRolesOperationCompleted Is Nothing) Then
                Me.TbRolConsultarRolesOperationCompleted = AddressOf Me.OnTbRolConsultarRolesOperationCompleted
            End If
            Me.InvokeAsync("TbRolConsultarRoles", New Object(-1) {}, Me.TbRolConsultarRolesOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbRolConsultarRolesOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbRolConsultarRolesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbRolConsultarRolesCompleted(Me, New TbRolConsultarRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbRolConsultarRol", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbRolConsultarRol(ByVal pRol As Rol) As Rol
            Dim results() As Object = Me.Invoke("TbRolConsultarRol", New Object() {pRol})
            Return CType(results(0),Rol)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbRolConsultarRolAsync(ByVal pRol As Rol)
            Me.TbRolConsultarRolAsync(pRol, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbRolConsultarRolAsync(ByVal pRol As Rol, ByVal userState As Object)
            If (Me.TbRolConsultarRolOperationCompleted Is Nothing) Then
                Me.TbRolConsultarRolOperationCompleted = AddressOf Me.OnTbRolConsultarRolOperationCompleted
            End If
            Me.InvokeAsync("TbRolConsultarRol", New Object() {pRol}, Me.TbRolConsultarRolOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbRolConsultarRolOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbRolConsultarRolCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbRolConsultarRolCompleted(Me, New TbRolConsultarRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbRolInsertarRol", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbRolInsertarRol(ByVal pRol As Rol) As String
            Dim results() As Object = Me.Invoke("TbRolInsertarRol", New Object() {pRol})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbRolInsertarRolAsync(ByVal pRol As Rol)
            Me.TbRolInsertarRolAsync(pRol, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbRolInsertarRolAsync(ByVal pRol As Rol, ByVal userState As Object)
            If (Me.TbRolInsertarRolOperationCompleted Is Nothing) Then
                Me.TbRolInsertarRolOperationCompleted = AddressOf Me.OnTbRolInsertarRolOperationCompleted
            End If
            Me.InvokeAsync("TbRolInsertarRol", New Object() {pRol}, Me.TbRolInsertarRolOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbRolInsertarRolOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbRolInsertarRolCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbRolInsertarRolCompleted(Me, New TbRolInsertarRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbRolActualizarRol", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbRolActualizarRol(ByVal pRol As Rol) As String
            Dim results() As Object = Me.Invoke("TbRolActualizarRol", New Object() {pRol})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbRolActualizarRolAsync(ByVal pRol As Rol)
            Me.TbRolActualizarRolAsync(pRol, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbRolActualizarRolAsync(ByVal pRol As Rol, ByVal userState As Object)
            If (Me.TbRolActualizarRolOperationCompleted Is Nothing) Then
                Me.TbRolActualizarRolOperationCompleted = AddressOf Me.OnTbRolActualizarRolOperationCompleted
            End If
            Me.InvokeAsync("TbRolActualizarRol", New Object() {pRol}, Me.TbRolActualizarRolOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbRolActualizarRolOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbRolActualizarRolCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbRolActualizarRolCompleted(Me, New TbRolActualizarRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbRolEliminarRol", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbRolEliminarRol(ByVal pRol As Rol) As String
            Dim results() As Object = Me.Invoke("TbRolEliminarRol", New Object() {pRol})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbRolEliminarRolAsync(ByVal pRol As Rol)
            Me.TbRolEliminarRolAsync(pRol, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbRolEliminarRolAsync(ByVal pRol As Rol, ByVal userState As Object)
            If (Me.TbRolEliminarRolOperationCompleted Is Nothing) Then
                Me.TbRolEliminarRolOperationCompleted = AddressOf Me.OnTbRolEliminarRolOperationCompleted
            End If
            Me.InvokeAsync("TbRolEliminarRol", New Object() {pRol}, Me.TbRolEliminarRolOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbRolEliminarRolOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbRolEliminarRolCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbRolEliminarRolCompleted(Me, New TbRolEliminarRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Rol
        
        Private idRolField As Integer
        
        Private descripcionField As String
        
        '''<comentarios/>
        Public Property IdRol() As Integer
            Get
                Return Me.idRolField
            End Get
            Set
                Me.idRolField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbRolConsultarRolesCompletedEventHandler(ByVal sender As Object, ByVal e As TbRolConsultarRolesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbRolConsultarRolesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbRolConsultarRolCompletedEventHandler(ByVal sender As Object, ByVal e As TbRolConsultarRolCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbRolConsultarRolCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Rol
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Rol)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbRolInsertarRolCompletedEventHandler(ByVal sender As Object, ByVal e As TbRolInsertarRolCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbRolInsertarRolCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbRolActualizarRolCompletedEventHandler(ByVal sender As Object, ByVal e As TbRolActualizarRolCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbRolActualizarRolCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbRolEliminarRolCompletedEventHandler(ByVal sender As Object, ByVal e As TbRolEliminarRolCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbRolEliminarRolCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
