'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
'
Namespace wsDetalleFactura
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsTbDetalleFacturaSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class wsTbDetalleFactura
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private TbDetalleFacturaConsultarDetallesFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbDetalleFacturaConsultarDetalleFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbDetalleFacturaInsertarDetalleFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbDetalleFacturaActualizarDetalleFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TbDetalleFacturaEliminarDetalleFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CapaPresentacion.My.MySettings.Default.CapaPresentacion_wsDetalleFactura_wsTbDetalleFactura
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event TbDetalleFacturaConsultarDetallesFacturaCompleted As TbDetalleFacturaConsultarDetallesFacturaCompletedEventHandler
        
        '''<remarks/>
        Public Event TbDetalleFacturaConsultarDetalleFacturaCompleted As TbDetalleFacturaConsultarDetalleFacturaCompletedEventHandler
        
        '''<remarks/>
        Public Event TbDetalleFacturaInsertarDetalleFacturaCompleted As TbDetalleFacturaInsertarDetalleFacturaCompletedEventHandler
        
        '''<remarks/>
        Public Event TbDetalleFacturaActualizarDetalleFacturaCompleted As TbDetalleFacturaActualizarDetalleFacturaCompletedEventHandler
        
        '''<remarks/>
        Public Event TbDetalleFacturaEliminarDetalleFacturaCompleted As TbDetalleFacturaEliminarDetalleFacturaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbDetalleFacturaConsultarDetallesFactura", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbDetalleFacturaConsultarDetallesFactura(ByVal pIdFactura As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TbDetalleFacturaConsultarDetallesFactura", New Object() {pIdFactura})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbDetalleFacturaConsultarDetallesFacturaAsync(ByVal pIdFactura As Integer)
            Me.TbDetalleFacturaConsultarDetallesFacturaAsync(pIdFactura, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbDetalleFacturaConsultarDetallesFacturaAsync(ByVal pIdFactura As Integer, ByVal userState As Object)
            If (Me.TbDetalleFacturaConsultarDetallesFacturaOperationCompleted Is Nothing) Then
                Me.TbDetalleFacturaConsultarDetallesFacturaOperationCompleted = AddressOf Me.OnTbDetalleFacturaConsultarDetallesFacturaOperationCompleted
            End If
            Me.InvokeAsync("TbDetalleFacturaConsultarDetallesFactura", New Object() {pIdFactura}, Me.TbDetalleFacturaConsultarDetallesFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbDetalleFacturaConsultarDetallesFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbDetalleFacturaConsultarDetallesFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbDetalleFacturaConsultarDetallesFacturaCompleted(Me, New TbDetalleFacturaConsultarDetallesFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbDetalleFacturaConsultarDetalleFactura", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbDetalleFacturaConsultarDetalleFactura(ByVal pDetalleFactura As DetalleFactura) As DetalleFactura
            Dim results() As Object = Me.Invoke("TbDetalleFacturaConsultarDetalleFactura", New Object() {pDetalleFactura})
            Return CType(results(0),DetalleFactura)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbDetalleFacturaConsultarDetalleFacturaAsync(ByVal pDetalleFactura As DetalleFactura)
            Me.TbDetalleFacturaConsultarDetalleFacturaAsync(pDetalleFactura, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbDetalleFacturaConsultarDetalleFacturaAsync(ByVal pDetalleFactura As DetalleFactura, ByVal userState As Object)
            If (Me.TbDetalleFacturaConsultarDetalleFacturaOperationCompleted Is Nothing) Then
                Me.TbDetalleFacturaConsultarDetalleFacturaOperationCompleted = AddressOf Me.OnTbDetalleFacturaConsultarDetalleFacturaOperationCompleted
            End If
            Me.InvokeAsync("TbDetalleFacturaConsultarDetalleFactura", New Object() {pDetalleFactura}, Me.TbDetalleFacturaConsultarDetalleFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbDetalleFacturaConsultarDetalleFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbDetalleFacturaConsultarDetalleFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbDetalleFacturaConsultarDetalleFacturaCompleted(Me, New TbDetalleFacturaConsultarDetalleFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbDetalleFacturaInsertarDetalleFactura", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbDetalleFacturaInsertarDetalleFactura(ByVal pDetalleFactura As DetalleFactura) As String
            Dim results() As Object = Me.Invoke("TbDetalleFacturaInsertarDetalleFactura", New Object() {pDetalleFactura})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbDetalleFacturaInsertarDetalleFacturaAsync(ByVal pDetalleFactura As DetalleFactura)
            Me.TbDetalleFacturaInsertarDetalleFacturaAsync(pDetalleFactura, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbDetalleFacturaInsertarDetalleFacturaAsync(ByVal pDetalleFactura As DetalleFactura, ByVal userState As Object)
            If (Me.TbDetalleFacturaInsertarDetalleFacturaOperationCompleted Is Nothing) Then
                Me.TbDetalleFacturaInsertarDetalleFacturaOperationCompleted = AddressOf Me.OnTbDetalleFacturaInsertarDetalleFacturaOperationCompleted
            End If
            Me.InvokeAsync("TbDetalleFacturaInsertarDetalleFactura", New Object() {pDetalleFactura}, Me.TbDetalleFacturaInsertarDetalleFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbDetalleFacturaInsertarDetalleFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbDetalleFacturaInsertarDetalleFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbDetalleFacturaInsertarDetalleFacturaCompleted(Me, New TbDetalleFacturaInsertarDetalleFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbDetalleFacturaActualizarDetalleFactura", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbDetalleFacturaActualizarDetalleFactura(ByVal pDetalleFactura As DetalleFactura) As String
            Dim results() As Object = Me.Invoke("TbDetalleFacturaActualizarDetalleFactura", New Object() {pDetalleFactura})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbDetalleFacturaActualizarDetalleFacturaAsync(ByVal pDetalleFactura As DetalleFactura)
            Me.TbDetalleFacturaActualizarDetalleFacturaAsync(pDetalleFactura, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbDetalleFacturaActualizarDetalleFacturaAsync(ByVal pDetalleFactura As DetalleFactura, ByVal userState As Object)
            If (Me.TbDetalleFacturaActualizarDetalleFacturaOperationCompleted Is Nothing) Then
                Me.TbDetalleFacturaActualizarDetalleFacturaOperationCompleted = AddressOf Me.OnTbDetalleFacturaActualizarDetalleFacturaOperationCompleted
            End If
            Me.InvokeAsync("TbDetalleFacturaActualizarDetalleFactura", New Object() {pDetalleFactura}, Me.TbDetalleFacturaActualizarDetalleFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbDetalleFacturaActualizarDetalleFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbDetalleFacturaActualizarDetalleFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbDetalleFacturaActualizarDetalleFacturaCompleted(Me, New TbDetalleFacturaActualizarDetalleFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TbDetalleFacturaEliminarDetalleFactura", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TbDetalleFacturaEliminarDetalleFactura(ByVal pDetalleFactura As DetalleFactura) As String
            Dim results() As Object = Me.Invoke("TbDetalleFacturaEliminarDetalleFactura", New Object() {pDetalleFactura})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TbDetalleFacturaEliminarDetalleFacturaAsync(ByVal pDetalleFactura As DetalleFactura)
            Me.TbDetalleFacturaEliminarDetalleFacturaAsync(pDetalleFactura, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TbDetalleFacturaEliminarDetalleFacturaAsync(ByVal pDetalleFactura As DetalleFactura, ByVal userState As Object)
            If (Me.TbDetalleFacturaEliminarDetalleFacturaOperationCompleted Is Nothing) Then
                Me.TbDetalleFacturaEliminarDetalleFacturaOperationCompleted = AddressOf Me.OnTbDetalleFacturaEliminarDetalleFacturaOperationCompleted
            End If
            Me.InvokeAsync("TbDetalleFacturaEliminarDetalleFactura", New Object() {pDetalleFactura}, Me.TbDetalleFacturaEliminarDetalleFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnTbDetalleFacturaEliminarDetalleFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.TbDetalleFacturaEliminarDetalleFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TbDetalleFacturaEliminarDetalleFacturaCompleted(Me, New TbDetalleFacturaEliminarDetalleFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DetalleFactura
        
        Private idFacturaField As Integer
        
        Private idDetalleFacturaField As Integer
        
        Private idServicioField As Integer
        
        Private precioUnitarioField As Double
        
        Private cantidadField As Integer
        
        '''<comentarios/>
        Public Property IdFactura() As Integer
            Get
                Return Me.idFacturaField
            End Get
            Set
                Me.idFacturaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IdDetalleFactura() As Integer
            Get
                Return Me.idDetalleFacturaField
            End Get
            Set
                Me.idDetalleFacturaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IdServicio() As Integer
            Get
                Return Me.idServicioField
            End Get
            Set
                Me.idServicioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrecioUnitario() As Double
            Get
                Return Me.precioUnitarioField
            End Get
            Set
                Me.precioUnitarioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Cantidad() As Integer
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbDetalleFacturaConsultarDetallesFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As TbDetalleFacturaConsultarDetallesFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbDetalleFacturaConsultarDetallesFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbDetalleFacturaConsultarDetalleFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As TbDetalleFacturaConsultarDetalleFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbDetalleFacturaConsultarDetalleFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DetalleFactura
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DetalleFactura)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbDetalleFacturaInsertarDetalleFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As TbDetalleFacturaInsertarDetalleFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbDetalleFacturaInsertarDetalleFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbDetalleFacturaActualizarDetalleFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As TbDetalleFacturaActualizarDetalleFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbDetalleFacturaActualizarDetalleFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub TbDetalleFacturaEliminarDetalleFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As TbDetalleFacturaEliminarDetalleFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TbDetalleFacturaEliminarDetalleFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
